TOTAL_TRADES = 100 # tổng số lần trade
MIN_SLEEP = 300  # seconds - random thời gian tối thiểu giữa các lần trade
MAX_SLEEP = 600  # seconds - random thời gian tối đa giữa các lần trade
TRADING_PAIR = "BTC_USDC_PERP"  # "ETH_USDC_PERP", "SOL_USDC_PERP", ...
TRADE_SIDE = "SHORT"  # "LONG" or "SHORT"
LEVERAGE_LIMIT = 20  # Max đòn bẩy: 50
TRADING_AMOUNT = 100  # USDC - tính cả đòn bẩy
LIMIT_PRICE_PERCENTAGE = 0.05  # đặt lệnh limit price cách giá hiện tại 0.05%
STOP_LOSS_USDC = 5  # Stop loss in USDC dựa theo TRADING_AMOUNT
TAKE_PROFIT_USDC = 10  # Take profit in USDC dựa theo TRADING_AMOUNT
AUTO_REPAY_BORROWS = True
